version: "3.7"
services:
  feecc-validator-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8084:8084"
    restart: always
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "~/.cache/pip/:/root/.cache/pip"
    environment:
      MONGO_CONNECTION_URL: ""  # Your MongoDB connection URI ending with /db-name
      IPFS_DISPLAY_GATEWAY_LINK: "https://gateway.ipfs.io/ipfs"
      IPFS_PARSING_GATEWAY_LINK: "https://multiagent.mypinata.cloud/ipfs"
      BLOCK_EXPLORER_LINK: "https://robonomics.subscan.io/extrinsic"